apiVersion : apps/v1
kind: Deployment
metadata:
  name: pod1 
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1 
    spec:
      containers:
        - name: pod1 
          image: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: pod1
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: pod1
